services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
        - action: sync+restart
          path: uv.lock
          target: /app/uv.lock
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - AWS_S3_ENDPOINT_URL=http://storage:3900
      - CELERY_BROKER_URL=redis://cache:6379/0
    restart: on-failure
  database:
    image: postgres:18.3@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    environment:
      POSTGRES_DB: lulzcasz_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: on-failure
  storage:
    image: dxflrs/garage:v2.2.0@sha256:45a61ce3f7c9c24fc23d9ed2b09b27ed560ab87b34605d175d5c588f539c24e4
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    restart: on-failure
  cache:
    image: redis:8.6.2@sha256:970b561d234882c50495c69ffae28f94b6ad8d526f91f9b4ccdd8031466e11a2
    ports:
      - 6379:6379
    command: redis-server
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: uv run celery -A lulzcasz_dev worker --loglevel=INFO --concurrency=2
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
        - action: sync+restart
          path: uv.lock
          target: /app/uv.lock
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - CELERY_BROKER_URL=redis://cache:6379/0
      - AWS_S3_ENDPOINT_URL=http://storage:3900
    restart: on-failure
