services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: uv run manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
        - action: sync+restart
          path: uv.lock
          target: /app/uv.lock
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - AWS_S3_ENDPOINT_URL=http://storage:3900
      - CELERY_BROKER_URL=redis://cache:6379/0
    restart: on-failure
  database:
    image: postgres:18.4@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
    environment:
      POSTGRES_DB: lulzcasz_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    restart: on-failure
  storage:
    image: dxflrs/garage:v2.3.0@sha256:866bd13ed2038ba7e7190e840482bc27234c4afaf77be8cfa439ae088c1e4690
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    restart: on-failure
  cache:
    image: redis:8.6.3@sha256:4d25e2fe601f7ffaeb4437cb6ced3518bc36edf34ebe98863c80836943d94529
    ports:
      - 6379:6379
    command: redis-server
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: uv run celery -A lulzcasz_dev worker --loglevel=INFO --concurrency=2
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /app
        - action: sync+restart
          path: uv.lock
          target: /app/uv.lock
    env_file:
      - .env
    environment:
      - DATABASE_HOST=database
      - CELERY_BROKER_URL=redis://cache:6379/0
      - AWS_S3_ENDPOINT_URL=http://storage:3900
    restart: on-failure
