metadata_dir = "/tmp/meta"
data_dir = "/tmp/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "13556022166d5123c3bffa8182d39763d45a2f2427cbee65c5961d0cfe6e9c32"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = "media.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "3V889khJexVenGA+zYNzJ3XJno7xfTceJNPlTlAOsYE="
metrics_token = "nal/3iUaamhGw1OVyh7SA4HJsQEf5CDejVeI+LPO1Mk="
