# Generated by Django 5.2.14 on 2026-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, verbose_name='cor')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'tecnologia',
                'abstract': False,
            },
        ),
    ]
