# Generated by Django 5.2.14 on 2026-06-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_technologies'),
        ('common', '0001_initial'),
        ('portfolio', '0002_technology_alter_project_technologies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
