# Generated by Django 5.2.15 on 2026-08-16 15:03

import sponsors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to=sponsors.models.sponsor_image_upload_to)),
            ],
        ),
    ]
