# Generated by Django 5.2.14 on 2026-05-28 15:37

import common.utils
import django.db.models.deletion
import taggit.managers
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('products', '0002_product_uuid'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'gênero',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=145, verbose_name='descrição')),
                ('cover', models.ImageField(blank=True, upload_to=common.utils.post_image_path, verbose_name='capa')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='conteúdo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('published_at', models.DateTimeField(editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='categoria')),
                ('post_genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.genre', verbose_name='gênero')),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='produtos')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('technologies', models.ManyToManyField(blank=True, related_name='posts', to='common.technology', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'post',
            },
        ),
    ]
