# Generated by Django 5.2.15 on 2026-08-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='description',
            field=models.CharField(blank=True, max_length=130),
        ),
    ]
