# Generated by Django 5.2.15 on 2026-08-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponsors.sponsor'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='articletranslation',
            unique_together={('language_code', 'slug'), ('language_code', 'title')},
        ),
    ]
