# Generated by Django 5.2.14 on 2026-06-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='technologies',
        ),
    ]
