# Generated by Django 5.2.14 on 2026-06-10 02:12

import common.utils.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, max_length=110, upload_to=common.utils.upload_to.post_image_path, verbose_name='capa'),
        ),
    ]
