# Generated by Django 5.2.15 on 2026-08-18 17:39

import blog.utils.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorytranslation_sponsor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, upload_to=blog.utils.upload_to.article_image_path),
        ),
    ]
