# Generated by Django 5.2.15 on 2026-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.TextField(blank=True),
        ),
    ]
