# Generated by Django 5.2.15 on 2026-06-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_category_options_alter_genre_options_and_more'),
        ('products', '0002_alter_affiliatelink_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
        migrations.CreateModel(
            name='PostProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('post', 'product')},
            },
        ),
    ]
