# Generated by Django 5.2.15 on 2026-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_products_postproduct'),
        ('products', '0002_alter_affiliatelink_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, through='blog.PostProduct', to='products.product'),
        ),
    ]
