# Generated by Django 5.2.15 on 2026-06-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
        migrations.DeleteModel(
            name='PostProduct',
        ),
    ]
