# Generated by Django 5.2.15 on 2026-06-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_products_delete_postproduct'),
        ('products', '0002_alter_affiliatelink_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
