# Generated by Django 5.2.15 on 2026-06-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
    ]
