# Generated by Django 5.2.14 on 2026-05-18 14:14

import about.utils.upload_to
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='nome')),
                ('link', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7, verbose_name='cor')),
                ('bg_color', models.CharField(max_length=7, verbose_name='cor do fundo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nome')),
                ('subtitle', models.CharField(max_length=128, verbose_name='subtítulo')),
                ('avatar', models.ImageField(upload_to=about.utils.upload_to.profile_avatar_path)),
                ('bio', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='HighlightPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'post em destaque',
                'verbose_name_plural': 'posts em destaque',
                'ordering': ['order', '-post__published_at'],
            },
        ),
    ]
