# Generated by Django 5.2.14 on 2026-06-02 15:55

import common.utils.upload_to
import portfolio.utils.upload_to
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, verbose_name='cor')),
                ('name', models.CharField(max_length=16, verbose_name='nome')),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nome')),
                ('subtitle', models.CharField(max_length=128, verbose_name='subtítulo')),
                ('avatar', models.ImageField(upload_to=portfolio.utils.upload_to.profile_avatar_path)),
                ('bio', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=145, verbose_name='descrição')),
                ('cover', models.ImageField(blank=True, upload_to=common.utils.upload_to.post_image_path, verbose_name='capa')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='conteúdo')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('repository', models.URLField(blank=True, null=True, verbose_name='repositório')),
                ('live', models.URLField(blank=True, null=True, verbose_name='ao vivo')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='common.technology', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'projeto',
            },
        ),
    ]
