# Generated by Django 5.2.14 on 2026-05-24 20:09

import common.utils
import portfolio.utils.upload_to
import taggit.managers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=7, verbose_name='cor')),
                ('name', models.CharField(max_length=16, verbose_name='nome')),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nome')),
                ('subtitle', models.CharField(max_length=128, verbose_name='subtítulo')),
                ('avatar', models.ImageField(upload_to=portfolio.utils.upload_to.profile_avatar_path)),
                ('bio', models.TextField(max_length=800)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=145, verbose_name='descrição')),
                ('cover', models.ImageField(blank=True, upload_to=common.utils.post_image_path, verbose_name='capa')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='conteúdo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('published_at', models.DateTimeField(editable=False, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('repository', models.URLField(blank=True, null=True, verbose_name='repositório')),
                ('live', models.URLField(blank=True, null=True, verbose_name='ao vivo')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='common.technology', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'projeto',
            },
        ),
    ]
