# Generated by Django 5.2.14 on 2026-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=32, unique=True)),
                ('color', models.CharField(max_length=7, verbose_name='cor')),
            ],
            options={
                'verbose_name': 'tecnologia',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.technology', verbose_name='tecnologias'),
        ),
    ]
